# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget libspatialindex::spatialindex libspatialindex::spatialindex_c)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target libspatialindex::spatialindex
add_library(libspatialindex::spatialindex SHARED IMPORTED)

# Create imported target libspatialindex::spatialindex_c
add_library(libspatialindex::spatialindex_c SHARED IMPORTED)

set_target_properties(libspatialindex::spatialindex_c PROPERTIES
  INTERFACE_LINK_LIBRARIES "libspatialindex::spatialindex"
)

# Import target "libspatialindex::spatialindex" for configuration "RelWithDebInfo"
set_property(TARGET libspatialindex::spatialindex APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(libspatialindex::spatialindex PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/share/multi-D/grid/libspatialindex/bin/libspatialindex.so.6.1.1"
  IMPORTED_SONAME_RELWITHDEBINFO "libspatialindex.so.6"
  )

# Import target "libspatialindex::spatialindex_c" for configuration "RelWithDebInfo"
set_property(TARGET libspatialindex::spatialindex_c APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(libspatialindex::spatialindex_c PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/share/multi-D/grid/libspatialindex/bin/libspatialindex_c.so.6.1.1"
  IMPORTED_SONAME_RELWITHDEBINFO "libspatialindex_c.so.6"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
